
package com.github.seraphain.examples.spring.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.github.seraphain.examples.spring.ws.beans.ObjectFactory;
import com.github.seraphain.examples.spring.ws.beans.TestReq;
import com.github.seraphain.examples.spring.ws.beans.TestRsp;
import com.github.seraphain.examples.spring.ws.beans.WsException_Exception;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "exampleServiceApi", targetNamespace = "http://seraphain.github.com/service")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExampleServiceApi {


    /**
     * 
     * @param testReq
     * @return
     *     returns com.github.seraphain.examples.spring.ws.beans.TestRsp
     * @throws WsException_Exception
     */
    @WebMethod
    @WebResult(name = "testRsp", targetNamespace = "http://seraphain.github.com/service", partName = "testRsp")
    public TestRsp test(
        @WebParam(name = "testReq", targetNamespace = "http://seraphain.github.com/service", partName = "testReq")
        TestReq testReq)
        throws WsException_Exception
    ;

}
