package com.github.seraphain.examples.cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2015-05-23T19:22:32.519+08:00
 * Generated source version: 3.1.0
 * 
 */
@WebService(targetNamespace = "http://cxf.examples.seraphain.github.com/", name = "CxfServer")
@XmlSeeAlso({ObjectFactory.class})
public interface CxfServer {

    @WebMethod
    @RequestWrapper(localName = "service", targetNamespace = "http://cxf.examples.seraphain.github.com/", className = "com.github.seraphain.examples.cxf.Service")
    @ResponseWrapper(localName = "serviceResponse", targetNamespace = "http://cxf.examples.seraphain.github.com/", className = "com.github.seraphain.examples.cxf.ServiceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String service(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
