
package com.github.seraphain.examples.spring.ws.beans;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "wsException", targetNamespace = "http://seraphain.github.com/service")
public class WsException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private WsException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public WsException_Exception(String message, WsException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public WsException_Exception(String message, WsException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.github.seraphain.examples.spring.ws.beans.WsException
     */
    public WsException getFaultInfo() {
        return faultInfo;
    }

}
